### ISSUE TITLE
Doesn't work on Azure SQL Databases

### ISSUE THREAD

**Issue by ShaneCourtrille** [mjswart/sqlblockedprocesses#5]
This script won't work on Azure SQL Databases due to the fact I can't place it on master and if I try placing it on another database and execute using this line

`EXEC sp_blocked_process_report_viewer @Source='bpr', @Type='TABLE';`

I receive this error:
```

Msg 208, Level 16, State 1, Procedure sp_blocked_process_report_viewer, Line 22 [Batch Start Line 124]
Invalid object name 'sys.server_event_sessions'.
```

**Comment by mjswart** [comment]
Thanks for your feedback Shane, 
You're right. The need for `sys.server_event_sessions` is there in order to read blocking data from extended events sessions. 
In a similar way, the function `fn_trace_gettable` is used to load blocking data from a file.
And `OPENROWSET` is used when trying to read from xml files.
All three of those methods don't work in Azure SQL Databases. 

So this tool is very much a tool built with the box version of SQL Server in mind. 
It *might* work, if you delete everything that is unrelated to TABLE sources. But I currently don't have any plans to support Azure SQL Databases

**Comment by mjswart-d2l** [comment]
Won't fix
